# Generated by Django 5.0.6 on 2024-06-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('login', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('lang', models.CharField(blank=True, max_length=2, null=True)),
                ('theme', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
