name: Python linting
on: [push, pull_request]
jobs:
  test:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install FeretUI
        run: pip install .[test]
      - name: Run ruff check
        run: ruff check feretui
