name: Tests
on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - main
    tags:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/setup-node@v4
         node-version: 'latest'
      - name: Install lessc
        run: sudo npm install -g less
      - name: Update pip
        run: pip install -U pip
      - name: Install FeretUI
        run: pip install -e .[test]
      - name: Run tests
        run: pytest --cov feretui --cov-report term-missing --cov-report lcov
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: ${{ github.job }}
          path-to-lcov: coverage.lcov

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
          path-to-lcov: coverage.lcov
          format: lcov
