name: Tests
on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - main
    tags:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update pip
        run: pip install -U pip
      - name: Install lcov
        run: pip install coverage-lcov
      - name: Install FeretUI
        run: pip install .[test]
      - name: Run tests
        run: pytest feretui
      - name: Generate lcov
        run: coverage-lcov
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: ${{ github.job }}
          path-to-lcov: lcov.info

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
          path-to-lcov: lcov.info
          format: lcov
